### ISSUE TITLE
Release request

### ISSUE THREAD

**Issue by ZhyliaievD** [DeviceFarmer/stf-device-db#8]
Hi
May I ask for a new release to include the following changes?
https://github.com/DeviceFarmer/stf-device-db/commit/756952f17d4564e52d46f6d2362bf6eb48c52602

**Comment by koral--** [comment]
@devicefarmer/stf-device-db 1.3.0 with that change is already released to npmjs.
If you mean the main package @devicefarmer/stf it is planned at the beginning of April.
